# Shrink default JVM heap.
esJavaOpts: "-Xmx128m -Xms128m"

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "512M"

# To allocate more space if above requests and limits aren't enough
# resources:
  # requests:
    # cpu: "500m"
    # memory: "2Gi"
  # limits:
    # cpu: "1000m"
    # memory: "5G"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "linode-block-storage"
  resources:
    requests:
