apiVersion: apps/v1
kind: Deployment
metadata:
  name: uswest-node
  labels:
    app: uswest-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs-apps
          image: lvaditya/node-web-app:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: linode-private
